services:
  - type: web
    name: FrameFlow
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT --timeout 300 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
